In [13]:
# q1

s=input("Enter a strings: ") # an input string with vowels and consonents
vowels="aeiouAEIOU"
countv=0 # to count the number of vowels
countc=0 # to count the number of consonents

for ch in s:
    if ch in vowels:
        countv+=1
    else:
        countc+=1

print("Vowels:",countv)
print("Consonants:",countc)


Enter a strings:  hi this is sravya


Vowels: 5
Consonants: 12


In [30]:
#q2

import numpy as np # using it to make the matric calculation easier

r1 = int(input("Enter rows of matrix A: ")) 
c1 = int(input("Enter columns of matrix A: "))
A = np.array([list(map(int, input().split())) for _ in range(r1)]) # putting both the row and the coloumn numbers in an array

r2 = int(input("Enter rows of matrix B: "))
c2 = int(input("Enter columns of matrix B: "))
B = np.array([list(map(int, input().split())) for _ in range(r2)])

if c1!=r2:
    print("Error") # checks if they are multiplicable , if they are the same they are multiplicable
else:
    product = np.dot(A, B) # multiplying A and B
    print("Product AB =\n", product)


Enter rows of matrix A:  3
Enter columns of matrix A:  3
 2 5 3
 2 7 4
 2 8 4
Enter rows of matrix B:  3
Enter columns of matrix B:  3
 5 9 7
 3 7 3
 5 9 6


Product AB =
 [[ 40  80  47]
 [ 51 103  59]
 [ 54 110  62]]


In [24]:
#q3

l1=input("Enter first list: ")
l2=input("Enter second list: ")
list1=l1.split() #we are splitting an input string
list2=l2.split()

common = set(list1)&set(list2) # adding only the common elements
print("Common elements:", common)
print("Number of common elements:", len(common))


Enter first list:  3 4 2 5
Enter second list:   3 6 4 4


Common elements: {'4', '3'}
Number of common elements: 2


In [31]:
#q4 

import numpy as np

r=int(input("Enter number of rows: "))
c=int(input("Enter number of columns: "))
print("Enter matrix elements row-wise:")
A = np.array([list(map(int, input().split())) for _ in range(r)])  # putting both the row and the coloumn numbers in an array

print("Transpose of matrix:\n",A.T)

Enter number of rows:  2
Enter number of columns:  2


Enter matrix elements row-wise:


 8 4
 2 5


Transpose of matrix:
 [[8 2]
 [4 5]]


In [25]:
# q5

import random
from statistics import mean, median, mode # a matematical function import funtion for mean mode and medium in statistics
nums = [random.randint(100, 150) for _ in range(100)] #takes random numbers from the range of 100-150
print("Numbers:", nums)
print("Mean:", mean(nums))
print("Median:", median(nums))
print("Mode:", mode(nums))


Numbers: [110, 144, 123, 123, 148, 106, 111, 149, 136, 105, 107, 133, 120, 133, 139, 112, 138, 138, 112, 123, 142, 110, 105, 138, 117, 144, 142, 140, 112, 137, 125, 124, 130, 110, 109, 136, 132, 146, 142, 101, 127, 103, 133, 106, 116, 124, 104, 125, 107, 113, 110, 128, 112, 112, 118, 116, 135, 104, 102, 125, 127, 131, 149, 139, 144, 105, 142, 131, 141, 139, 125, 100, 123, 138, 130, 121, 120, 124, 105, 150, 139, 150, 148, 133, 144, 109, 119, 104, 127, 132, 115, 114, 100, 107, 124, 116, 138, 105, 150, 108]
Mean: 124.38
Median: 124.0
Mode: 105
