In [57]:
## Q1 Need to load 2 seperate matrics, x=observations, y=output(prices) ,rank of the feuture matrix, and pseudo inverse to find the cost of each product
import pandas as pd
from numpy.linalg import matrix_rank,pinv
import numpy as np
file_path='Lab2 Session Data.xlsx'
df=pd.read_excel(file_path,sheet_name=0)
A=df[['Candies (#)','Mangoes (Kg)','Milk Packets (#)','Payment (Rs)']].to_numpy()
print("The rank of matrix A(feature+output):",matrix_rank(A))
X=df[['Candies (#)','Mangoes (Kg)','Milk Packets (#)']].to_numpy()
print("The observation matrix is(Feature Columns):\n",X)
print("The dimentionility of X:",X.shape)
print("The number of vectors in the matrix X:",X.shape[1])
print("The rank of matrix X(feature):",matrix_rank(X))
Y=df[['Payment (Rs)']].to_numpy()
print("The result/output matrix is(Output):\n",Y)
print("The dimentionility of Y:",Y.shape)
print("The number of vectors in the matrix Y:",Y.shape[1])
print("The cost of each product:",pinv(Y))


# Q2 All the customer with price above 200-Rich and others as poor
from sklearn.tree import DecisionTreeClassifier
x=df[['Payment (Rs)']]
y=np.where(df['Payment (Rs)']>200,'Rich','Poor')
clf = DecisionTreeClassifier()
clf.fit(x,y)
print("Predict all the customers who are rich/poor:",clf.predict(x))

The rank of matrix A(feature+output): 3
The observation matrix is(Feature Columns):
 [[20  6  2]
 [16  3  6]
 [27  6  2]
 [19  1  2]
 [24  4  2]
 [22  1  5]
 [15  4  2]
 [18  4  2]
 [21  1  4]
 [16  2  4]]
The dimentionility of X: (10, 3)
The number of vectors in the matrix X: 3
The rank of matrix X(feature): 3
The result/output matrix is(Output):
 [[386]
 [289]
 [393]
 [110]
 [280]
 [167]
 [271]
 [274]
 [148]
 [198]]
The dimentionility of Y: (10, 1)
The number of vectors in the matrix Y: 1
The cost of each product: [[0.00053988 0.00040421 0.00054967 0.00015385 0.00039162 0.00023357
  0.00037903 0.00038323 0.000207   0.00027693]]
Predict all the customers who are rich/poor: ['Rich' 'Rich' 'Rich' 'Poor' 'Rich' 'Poor' 'Rich' 'Rich' 'Poor' 'Poor']


In [ ]:
#Q3